import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

//* Components
import Navbar from '@/components/common/nav';
import Footer from '@/components/common/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Metub creator blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
