import '@/styles/globals.css';
import type { Metadata } from 'next';
//* Components
import Footer from '@/components/common/footer';
import { poppins } from '@/app/fonts';

export const metadata: Metadata = {
  title: 'Metub creator blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
